<a href="https://colab.research.google.com/github/aimldlnlp/Linear-Regression-with-Python/blob/main/Learner_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1: Introduction

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# Task 2: Dataset

Real estate agent table:

|Area|Distance|Price|
|---|---|---|
|70|3|21200|
|50|1|22010|
|120|9|24305|
|100|2|31500|

You can write the relationship with a 2-variable linear equation:

$
\begin{equation}
y = b + w_1.x_1 + w_2.x_2
\end{equation}
$

In a vector form:

$
\begin{equation}
y = b + (w_1 w_2).\binom{x_1}{x_2}
\end{equation}
$

Where
$
\begin{equation}
W = (w_1 w_2)
\end{equation}
$
and
$
\begin{equation}
X = \binom{x_1}{x_2}
\end{equation}
$

In [3]:
def generate_examples(num=1000):
    W = [1.0, -3.0]
    b = 1.0

    W = np.reshape(W, (2,1))
    X = np.random.randn(num, 2)
    y = np.dot(X, W) + b
    y = np.reshape(y, (num, 1))
    return X, y

In [4]:
X, y = generate_examples()

In [5]:
print(X.shape)
print(y.shape)

(1000, 2)
(1000, 1)


In [7]:
print(X[:5])
print(y[:5])

[[-0.20606728 -0.31562631]
 [-0.84995937 -1.68242993]
 [-0.27210273  0.30066057]
 [ 0.16035073 -1.90419292]
 [ 0.28684697  0.27430541]]
[[ 1.74081163]
 [ 5.19733043]
 [-0.17408445]
 [ 6.8729295 ]
 [ 0.46393074]]


# Task 3: Initialize Parameters

The loss over **m** examples:

$
\begin{equation}
J = \frac{1}{2m} \sum_{i=1}^{m} (y - \hat{y})^2
\end{equation}
$

The objective of the gradient descent algorithm is to minimize this loss value.

Gradient Descent Objective is to
$
\begin{equation}
min(J)
\end{equation}
$

In [9]:
class Model:
  def __init__(self, num_features):
    self.num_features = num_features
    self.W = np.random.randn(num_features, 1)
    self.b = np.random.randn()

In [10]:
model = Model(2)
print(model.W)
print(model.b)

[[-0.19148305]
 [-1.18122859]]
-2.4634690813674847


# Task 4: Forward Pass

The gradient descent algorithm can be simplified in 4 steps:

1. Get predictions y_hat for X with current values of W and b.
2. Compute the loss between y and y_hat
3. Find gradients of the loss with respect to parameters W and b
4. Update the values of W and b by subtracting the gradient values obtained in the previous step

Let's simplify our linear equation a bit more for an example:
$
\begin{equation}
y = wx
\end{equation}
$

Let's plot J as a function of w

![Loss vs Param](JvsW.png)

The gradients of loss with respect to w:

\begin{equation}
\frac{dJ}{dw} = \frac{\delta{J}}{\delta{w}} = \lim_{\epsilon \to 0} \frac{J(w + \epsilon) - J(w)}{\epsilon}
\end{equation}

In [15]:
class Model(Model):
    def forward_pass(self, X):
      y_hat = np.dot(X, self.W) + self.b
      return y_hat

In [16]:
y_hat = Model(2).forward_pass(X)
print(y_hat.shape)

(1000, 1)


# Task 5: Compute Loss

The loss over **m** examples:

$
\begin{equation}
J = \frac{1}{2m} \sum_{i=1}^{m} (y - \hat{y})^2
\end{equation}
$

# Task 6: Backward Pass

The gradient of loss with respect to bias can be calculated with:

$
\begin{equation}
\frac{dJ}{db} = \frac{1}{m} \sum_{i=1}^{m} (\hat{y^{(i)}} - y^{(i)})
\end{equation}
$

$
\begin{equation}
\frac{dJ}{dW_j} = \frac{1}{m} \sum_{i=1}^{m} (\hat{y^{(i)}} - y^{(i)}).x_j^{(i)}
\end{equation}
$

# Task 7: Update Parameters

# Task 8: Training Loop

# Task 9: Predictions